export const categories = [
  {
    name: 'Продуктовые магазины',
    subCategories: [
      'Хлеб, выпечка',
      'Мясо, птица',
      'Рыба, морепродукты',
      'Колбаса, сосиски',
      'Молочный прилавок',
      'Овощи, фрукты',
      'Сладости',
      'Полуфабрикаты',
      'Вода, напитки',
      'Бакалея',
      'Для детей',
      'Для животных',
      'Гигиена, уборка',
      'Разное',
    ],
  },
  {
    name: 'Хоз. магазины',
    subCategories: [],
  },
  {
    name: 'Рестораны',
    subCategories: [],
  },
  {
    name: 'Аптеки',
    subCategories: [],
  },
  {
    name: 'Фаст фуд',
    subCategories: [],
  },
  {
    name: 'Для детей',
    subCategories: [],
  },
  {
    name: 'Ремонт',
    subCategories: [],
  },
  {
    name: 'Хобби',
    subCategories: [],
  },
  {
    name: 'Для дома',
    subCategories: [],
  },
  {
    name: 'Электроника',
    subCategories: [],
  },
  {
    name: 'Рынки',
    subCategories: [],
  },
  {
    name: 'Спорт',
    subCategories: [],
  },
  {
    name: 'Канцелярия',
    subCategories: [],
  },
  {
    name: 'Цветы',
    subCategories: [],
  },
  {
    name: 'Зоо',
    subCategories: [],
  },
  {
    name: 'Красота',
    subCategories: [],
  },
  {
    name: 'Разное',
    subCategories: [],
  },
];

export const allPlaces = [
  {
    address: 'Пролетарская 32',
    category: 'Продуктовые магазины',
    id: 1,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 31',
    category: 'Продуктовые магазины',
    id: 2,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 33',
    category: 'Продуктовые магазины',
    id: 3,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 34',
    category: 'Продуктовые магазины',
    id: 4,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 35',
    category: 'Продуктовые магазины',
    id: 5,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 36',
    category: 'Продуктовые магазины',
    id: 6,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 37',
    category: 'Продуктовые магазины',
    id: 7,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 38',
    category: 'Продуктовые магазины',
    id: 8,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит',
    slug: 'magnit',
  },
  {
    address: 'Пролетарская 39',
    category: 'Хоз. магазины',
    id: 9,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 40',
    category: 'Хоз. магазины',
    id: 10,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 41',
    category: 'Хоз. магазины',
    id: 11,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 42',
    category: 'Хоз. магазины',
    id: 12,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 43',
    category: 'Хоз. магазины',
    id: 13,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 44',
    category: 'Хоз. магазины',
    id: 14,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 45',
    category: 'Хоз. магазины',
    id: 15,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Пролетарская 46',
    category: 'Хоз. магазины',
    id: 16,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Магнит Косметикс',
    slug: 'magnit-cosmetics',
  },
  {
    address: 'Индустриальная 47',
    category: 'Продуктовые магазины',
    id: 17,
    imageUrl: 'https://loremflickr.com/320/240/',
    name: 'Пятерочка',
    slug: 'pyaterochka',
  },
];

export const prices = [
  {
    category: 'Продуктовые магазины',
    name: 'Магнит',
    products: [
      {
        category: 'Хлеб, выпечка',
        imageUrl: 'https://loremflickr.com/320/240/',
        name: 'Батон',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: 'Хлеб',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: 'Булка',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: ' Батон нарезка',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: 'Батон белый',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: 'Батон молочный',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Сладости',
        name: 'Snickers',
        price: '56',
        quantity: '100г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: 'Батон с семечками',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Хлеб, выпечка',
        name: 'Батон утренний',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Мясо, птица',
        name: 'Test',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
      {
        category: 'Мясо, птица',
        name: 'Test утренний',
        price: '56',
        quantity: '400г',
        storeName: 'Магнит',
      },
    ],
    slug: 'magnit',
  },
  {
    category: 'Продуктовые магазины',
    name: 'Пятёрочка',
    products: [
      {
        category: 'Хлеб, выпечка',
        name: 'Хлебец',
        price: '25',
        quantity: '250г',
        storeName: 'Пятёрочка',
      },
    ],
    slug: 'pyaterochka',
  },
];
